services:
  - type: web
    name: venra
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn venra.wsgi:application"
    envVars:
      - key: DEBUG
        value: "False"
      - key: SECRET_KEY
        generateValue: true
      - key: ALLOWED_HOSTS
        value: venra.onrender.com
